vol1/core/urls.py
"""
MIT License

Copyright © 2024 louismiyanaga

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
"""

from django.urls import path

from .views import *

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('item/<int:pk>/', ItemView.as_view(), name='item'), # pkは商品のpk
    path('cart/<int:pk>/', CartView.as_view(), name='cart'), # pkはユーザーのpk
    path('delete_cart_item/<int:pk>/', DeleteCartItemView.as_view(), name='delete_cart_item'),  # pkはユーザーのpk
    path('order/', OrderView.as_view(), name='order'),
    path('success/', SuccessView.as_view(), name='success'),
]

vol1/mysite/urls.py
"""
URL configuration for mysite project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/5.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
]
# 以下記述がないと、アップロードされた商品画像がきちんと表示されません
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vol1/core/models.py
"""
MIT License

Copyright © 2024 louismiyanaga

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
"""

from django.conf import settings
from django.db import models

"""
---------------------------
ユーザーモデルの読み込み方法３種
---------------------------

1. settingsファイルから取得
from django.conf import settings
User = settings.AUTH_USER_MODEL

2. get_user_modelで取得
from django.contrib.auth import get_user_model
User = get_user_model()

3. 直接インポートして取得
from accounts.models import CustomUser

"""


User = settings.AUTH_USER_MODEL


class Category(models.Model):
    name = models.CharField('カテゴリ名', max_length=10)

    class Meta:
        verbose_name = '商品カテゴリ'
        verbose_name_plural = '商品カテゴリ'
    
    def __str__(self):
        return self.name


class Item(models.Model):
    name = models.CharField('商品名', max_length=100)
    price = models.PositiveIntegerField('価格')
    description = models.TextField('商品説明', blank=True, null=True)
    image = models.ImageField('商品画像', upload_to='item_images/', blank=True, null=True)
    category = models.ForeignKey(to=Category, on_delete=models.SET_DEFAULT, default=1, verbose_name='商品カテゴリ')

    class Meta:
        verbose_name = '商品'
        verbose_name_plural = '商品'
    
    def __str__(self):
        return self.name


class CartItem(models.Model):
    item = models.ForeignKey(to=Item, on_delete=models.CASCADE, verbose_name='商品')
    quantity = models.PositiveIntegerField('個数', default=1)
    
    class Meta:
        verbose_name = 'カートアイテム'
        verbose_name_plural = 'カートアイテム'
    
    def __str__(self):
        return f"{self.quantity}個の{self.item.name}"
    
    @property
    def total_price(self):
        """
        カートアイテムの合計金額を算出するメソッドです。
        """
        return self.item.price * self.quantity


class Cart(models.Model):
    cart_items = models.ManyToManyField(to=CartItem, blank=True, verbose_name='カートアイテム') # ManyToManyFieldにおいてnull=Trueは無意味のため不要です（右記警告が出ます → core.Cart.cart_items: (fields.W340) null has no effect on ManyToManyField.）
    
    class Meta:
        verbose_name = 'カート'
        verbose_name_plural = 'カート'
    
    def __str__(self):
        # CustomUserモデルのcartフィールドに related_name='cart_user' と指定したことで
        # 以下のように self.cart_user でユーザーオブジェクトを呼び出すことが可能になります
        return f"{self.cart_user.username}のカート"

    def add_cart_item(self, new_cart_item):
        """
        カートアイテムをカートに追加するメソッドです。
        [内容]
        1. すでに商品がカートに存在する場合は、その商品のquantityを増やすだけの処理
        2. そうでなければ、新たにカートアイテムを追加する処理
        """
        # 1. すでに商品がカートに存在する場合
        if new_cart_item.item in [cart_item.item for cart_item in self.cart_items.all()]:
            original_cart_item = self.cart_items.get(item_id=new_cart_item.item.id)
            original_cart_item.quantity += new_cart_item.quantity
            original_cart_item.save()
        # 2. そうでない場合
        else:
            new_cart_item.save()
            self.cart_items.add(new_cart_item) # ManyToManyの場合は忘れずにadd()を行うこと
    
    @property
    def total_price(self):
        """
        カートの中にある全カートアイテムの総額を算出するメソッドです。
        """
        return sum([cart_item.total_price for cart_item in self.cart_items.all()])


class Order(models.Model):
    order_user = models.ForeignKey(to=User, on_delete=models.CASCADE, verbose_name='注文ユーザー') # ユーザーが削除されても注文履歴を残したい場合は on_delete=models.SET_NULL にします
    order_items = models.ManyToManyField(to=CartItem, blank=True, verbose_name='注文商品')
    order_price = models.PositiveIntegerField('注文総額')
    ordered_date = models.DateTimeField('注文日', auto_now=True)

    class Meta:
        verbose_name = '注文'
        verbose_name_plural = '注文'
    
    def __str__(self):
        return f"{self.order_user.username}様の注文（{self.ordered_date}）"
    

vol1/core/forms.py
"""
MIT License

Copyright © 2024 louismiyanaga

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
"""

from django import forms

from .models import Category


class SearchForm(forms.Form):
    def __init__(self, *args, **kwargs):
        """
        inputタグにclass属性を追加します。
        """
        super().__init__(*args, **kwargs)
        self.fields['category'].widget.attrs.update({'class': 'form-select'})

    category = forms.ModelChoiceField(queryset=Category.objects, label='カテゴリ', empty_label='選択してください')

vol1/core/views.py
"""
MIT License

Copyright © 2024 louismiyanaga

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
"""

from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import DeleteView, DetailView, ListView
from django.views.generic.base import TemplateView, View

import stripe

from .forms import SearchForm
from .models import Item, CartItem, Order


stripe.api_key = settings.STRIPE_SECRET_KEY


User = get_user_model()


class OnlyYouMixin(UserPassesTestMixin):
    """
    以下いずれかの場合のみアクセスを許可するMixinです。
    
    'ユーザーのpkがURLのpkと一致する' or 'ユーザーがスーパーユーザーである'
    """
    def test_func(self):
        user = self.request.user
        return (user.id == self.kwargs['pk']) or (user.is_superuser)
    

class HomeView(ListView):
    template_name = "core/home.html"
    model = Item
    paginate_by = 6
    
    def get_context_data(self, **kwargs):
        """
        デフォルトでListViewが持っているget_context_dataメソッドを編集し、
        テンプレート側で{{form}}が使えるようにオーバーライドします。
        """
        context = super().get_context_data(**kwargs)
        context["form"] = SearchForm
        return context
    
    def get_queryset(self):
        """
        デフォルトでListViewが持っているget_querysetメソッドを編集し、
        特定のカテゴリに一致する商品群のみを返すようオーバーライドします。
        """
        items = super().get_queryset()
        q_category = self.request.GET.get('category')
        if q_category is not None:
            items = items.filter(category=q_category)
        return items


class ItemView(DetailView):
    template_name = "core/item.html"
    model = Item

    def get_success_url(self):
        """
        ユーザー専用のカートページURL(/cart/user_pk/)を取得するメソッドです。
        """
        user_pk = self.request.user.id
        return reverse_lazy('cart', kwargs={'pk': user_pk}) # kwargsの部分は args=(user_pk,) としてもOK
    
    def post(self, *args, **kwargs):
        """
        'カートに追加'ボタンが押された時(=POSTリクエストが送信された時)
        カートアイテム(商品と購入数)をカートに追加するためのメソッドです。
        DetailViewはpostメソッドを持っていないので、新たに作成します。
        [手順]
        1. HTMLのformから商品のpkとquantityの情報を取得
        2. 取得した情報をもとにカートアイテムを作成
        3. 作成したカートアイテムをユーザーのカートに追加
        4. カートページにリダイレクト
        """
        # 1. HTMLのformから商品のpkとquantityの情報を取得
        item_pk = self.request.POST.get('item_pk')
        quantity = int(self.request.POST.get('quantity'))
        # 2. 取得した情報をもとにカートアイテムを作成
        item = Item.objects.get(id=item_pk)
        cart_item = CartItem(item=item, quantity=quantity)
        # 3. 作成したカートアイテムをユーザーのカートに追加
        user = self.request.user
        user.cart.add_cart_item(cart_item)
        # 4. カートページにリダイレクト
        return redirect(self.get_success_url())


class CartView(LoginRequiredMixin, OnlyYouMixin, DetailView):
    template_name = "core/cart.html"
    model = User
    context_object_name = 'cart'

    def get_object(self, queryset=None):
        """
        デフォルトでDetailViewが持っているget_objectメソッドを編集します。
        modelにユーザーモデルを指定しているので、このままではテンプレートから
        取得されるオブジェクトはユーザーオブジェクトになります。
        カートオブジェクトを取り出せるように、以下の通りオーバーライドします。
        """
        user = super().get_object(queryset)
        return user.cart


class DeleteCartItemView(LoginRequiredMixin, OnlyYouMixin, DeleteView):
    model = User

    def get_object(self, queryset=None):
        """
        デフォルトでDeleteViewが持っているget_objectメソッドを編集します。
        modelにユーザーモデルを指定しているので、このままでは削除対象となる
        オブジェクトはユーザーになります。
        ユーザーではなく、カートに入っている"特定のカートアイテム"を削除対象
        とするよう、以下の通りオーバーライドします。
        [手順]
        1. formからカートアイテムのpkを取得
        2. カートの中から、取得したpkと一致するカートアイテムを取得
        """
        user = super().get_object(queryset)
        # 1. formからカートアイテムのpkを取得
        cart_item_pk = self.request.POST['cart_item_pk']
        # 2. カートの中から、取得したpkと一致するカートアイテムを取得
        cart_item = user.cart.cart_items.get(id=cart_item_pk)
        return cart_item
    
    def get_success_url(self):
        """
        ユーザー専用のカートページURL(/cart/user_pk/)を取得するメソッドです。
        """
        user_pk = self.request.user.id
        return reverse_lazy('cart', kwargs={'pk': user_pk}) # kwargsの部分は args=(user_pk,) としてもOK


class OrderView(View):
    def post(self, *args, **kwargs):
        """
        '購入へ進む'ボタンが押された時(=POSTリクエストが送信された時)
        大きく分けて以下の２つの処理が実行されるメソッドです。

        1. Django側の処理
        2. Stripe決済処理
        
        """
        
        """
        --------------------------------------------------------------
        1. Django側の処理
        --------------------------------------------------------------
        
        Orderオブジェクトを作ると同時にユーザーのカートを空にします。
        [手順]
        1-1. Orderオブジェクトを作成
        1-2. カートの中身(cart_items)をOrderオブジェクトのorder_itemsにコピー
        1-3. カートの中身をリセット
        """
        # 1-1. Orderオブジェクトを作成
        order_user = self.request.user
        order_cart = order_user.cart
        order_obj = Order.objects.create(
            order_user=order_user,
            order_price=order_cart.total_price,
        )
        # 1-2. カートの中身(cart_items)をOrderオブジェクトのorder_itemsにコピー
        # 右記のようにも記述できます: order_obj.order_items.add(*order_cart.cart_items.all())
        for cart_item in order_cart.cart_items.all():
            order_obj.order_items.add(cart_item)
        # 1-3. カートの中身をリセット
        order_cart.cart_items.clear()
        
        """
        --------------------------------------------------------------
        2. Stripe決済処理
        --------------------------------------------------------------
        
        ユーザーをStripeの決済ページにリダイレクトさせます。
        [手順]
        2-1. line_items(購入情報のリスト)を作成
        2-2. checkout_sessionを作成
        2-3. 決済ページにリダイレクト
        """
        # 2-1. line_items(購入情報のリスト)を作成
        line_items = []
        for order_item in order_obj.order_items.all():
            line_item = {
                'price_data': {
                    'currency': 'jpy',
                    'unit_amount': order_item.item.price,
                    'product_data': {
                        'name': order_item.item.name,
                    }
                },
                'quantity': order_item.quantity,
            }
            line_items.append(line_item)
        # 2-2. checkout_sessionを作成
        try:
            checkout_session = stripe.checkout.Session.create(
                line_items=line_items,
                mode='payment',
                phone_number_collection={'enabled': True}, # 任意
                shipping_address_collection={'allowed_countries': ['JP']}, # 任意
                success_url=settings.MYSITE_DOMAIN + '/success/',
            )
        except Exception as e:
            return str(e)
        # 2-3. 決済ページにリダイレクト
        return redirect(checkout_session.url)


class SuccessView(TemplateView):
    template_name = "core/success.html"

vol1/templates/core/cart.html
{% comment %} 
MIT License

Copyright © 2024 louismiyanaga

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE. 
{% endcomment %}

{% extends "base.html" %}


{% block title %}カート{% endblock title %}


{% block content %}

<div class="mx-auto" style="max-width: 960px">
    
    {% if cart.cart_items.exists %}
    {# Table of cart contents #}
    <table class="table align-middle text-center">
        <thead class="table-dark">
            <tr>
                <th scope="col">商品名</th>
                <th scope="col">単価</th>
                <th scope="col">購入数</th>
                <th scope="col">合計</th>
            </tr>
        </thead>
        <tbody>
            {% for cart_item in cart.cart_items.all %}
            {# ---------- Each cart item ---------- #}
            <tr>
                <td>{{ cart_item.item.name }}</td>
                <td>{{ cart_item.item.price }}円</td>
                <td>{{ cart_item.quantity }}</td>
                <td class="text-end">{{ cart_item.total_price }}円
                    <form action="{% url 'delete_cart_item' user.id %}" method="post" class="d-inline">{% csrf_token %}
                        <input type="hidden" name="cart_item_pk" value="{{ cart_item.id }}">
                        <button type="submit" class="btn btn-warning btn-sm ms-3">削除</button>
                    </form>
                </td>
            </tr>
            {# ---------- Each cart item ---------- #}
            {% endfor %}
            <tr>
                <td class="text-end fw-bolder fs-5" colspan="4">総額：{{ cart.total_price }}円</td>
            </tr>
        </tbody>
    </table>
    {# Continue or checkout button #}
    <div class="text-center">
        <form action="{% url 'order' %}" method="POST">{% csrf_token %}
            <a href="{% url 'home' %}" class="btn btn-secondary">ショッピングを続ける</a>
            <button type="submit" class="btn btn-dark">購入へ進む</a>
        </form>
    </div>
    {% else %}
    <div class="text-center">
        <p>カートは空です。</p>
        <a href="{% url 'home' %}" class="btn btn-secondary">商品を探す</a>
    </div>
    {% endif %}

</div>
    
{% endblock content %}

vol1/templates/core/home.html
{% comment %} 
MIT License

Copyright © 2024 louismiyanaga

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE. 
{% endcomment %}

{% extends "base.html" %}


{% block title %}ホーム{% endblock title %}


{% block header %}{% include "_header.html" %}{% endblock header %}


{% block content %}

{# ITEM SEARCH FORM #}
<div class="mx-auto text-center mb-5" style="max-width: 300px">
    <p>カテゴリを絞って商品を検索↓</p>
    <form action="" method="GET" class="row">
        <div class="col-8">
            {{ form.category }}
        </div>
        <div class="col-4">
            <button type="submit" class="btn btn-outline-secondary"><i class="bi bi-search me-1"></i>検索</button>
        </div>
    </form>
</div>

{# ITEM LIST #}
<div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
    {% for item in item_list %}
    {# -------------------- Each item card -------------------- #}
    <div class="col mb-5">
        <div class="card h-100">
            {# Category badge #}
            <div class="badge bg-dark text-white position-absolute" style="top:0.5rem; right:0.5rem">{{ item.category }}</div>
            {# Item image #}
            {% if item.image %}
            <img class="card-img-top" src="{{ item.image.url }}" alt="{{ item.name }}" style="height:150px;object-fit:cover" />
            {% else %}
            <img class="card-img-top" src="https://dummyimage.com/450x300/dee2e6/6c757d.jpg" alt="..." />
            {% endif %}
            {# Item info #}
            <div class="card-body p-4">
                <div class="text-center">
                    <h5 class="fw-bolder">{{ item.name }}</h5>
                    <p>{{ item.price }}円</p>
                </div>
            </div>
            {# Button #}
            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent text-center">
                <a class="btn btn-outline-dark mt-auto" href="{% url 'item' item.id %}">詳細を見る</a>
            </div>
        </div>
    </div>
    {# -------------------- Each item card -------------------- #}
    {% empty %}
    <p>商品がありません。</p>
    {% endfor %}
</div>

{# PAGINATION #}
<nav aria-label="Page navigation">
    <ul class="pagination justify-content-center">
        {# Previous page #}
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a href="?page={{ page_obj.previous_page_number }}" class="page-link" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link"><span aria-hidden="true">&laquo;</span></a>
        </li>
        {% endif %}
        {# Number pages #}
        {% for page_num in page_obj.paginator.page_range %}
            {% if page_num == page_obj.number %}
            <li class="page-item disabled">
                <a class="page-link">{{ page_num }}</a>
            </li>
            {% else %}
            <li class="page-item">
                <a href="?page={{ page_num }}" class="page-link">{{ page_num }}</a>
            </li>
            {% endif %}
        {% endfor %}
        {# Next page #}
        {% if page_obj.has_next %}
        <li class="page-item">
            <a href="?page={{ page_obj.next_page_number }}" class="page-link" aria-label="Next"><span aria-hidden="true">&raquo;</span></a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link"><span aria-hidden="true">&raquo;</span></a>
        </li>
        {% endif %}
    </ul>
</nav>

{% endblock content %}

vol1/templates/core/success.html
{% comment %} 
MIT License

Copyright © 2024 louismiyanaga

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE. 
{% endcomment %}

{% extends 'base.html' %}


{% block title %}決済完了{% endblock title %}


{% block content %}

<div class="text-center">
    <p>決済処理が正常に行われました。お買い上げありがとうございました。</p>
    <a href="{% url 'home' %}" class="btn btn-secondary">ホームに戻る</a>
</div>

{% endblock content %}